### ISSUE TITLE
Mirror symmetry problem arises if the parent part is also attached using mirror symmetry

### ISSUE THREAD

**Issue by linuxgurugamer** [blowfishpro/B9PartSwitch#139] opened 2019-04-13 01:09 UTC
The new setting mirrorSymmetrySubtype works perfectly when using node attachment, but it should be disabled when in surface attachment. See the following images which try to make it clear:

 

Using the "right" setting (mirrorSymmetrySubtype = Left):

  https://i.imgur.com/zJtd8vv.png
 

using the "left" setting (mirrorSymmetrySubtype = Right):

https://i.imgur.com/TQWuES1.png
 

using the "RightSurface" setting (no mirrorsymmetrySubtype specified):

https://i.imgur.com/h1sgwAv.png

using the "leftSurface" setting, no mirrorSymmetrySubtype set:

https://i.imgur.com/h1sgwAv.png

**Comment by linuxgurugamer** [comment] 2019-04-13 01:21
Additional note:  Not sure if related, but:
an elvon attached in node attachment mode and mirrored has the deploy direction reversed on the mirrored one, but surface attachment is fine

**Comment by blowfishpro** [comment] 2019-06-10 02:34
I think we discussed this, the problem is slightly more complicated than surface attached vs stack attached, but also it can be fixed with what's already there.  Do we still need this issue?

**Comment by linuxgurugamer** [comment] 2019-06-10 03:20
Not sure, it still isn't working for me in my tests.  How can it be fixed with what's there?

**Comment by blowfishpro** [comment] 2019-08-04 05:42
Resolved over direct messages

**Closed by blowfishpro** 2019-08-04 05:42 UTC
